### PR TITLE
Update the client to the 2.7 release.

### PR DESCRIPTION
**Pull request by jamesmharvey**
Update our vendored version of gopkg.in/zorkian/go-datadog-api.v2 to use
the version 2.7 release, which has the fix we need for #33

### CODE REVIEW

**Comment by jamesmharvey** [comment]
test output:

```
$ make testacc TEST=./datadog
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./datadog -v  -timeout 120m
=== RUN   TestDatadogDowntime_import
--- PASS: TestDatadogDowntime_import (3.95s)
=== RUN   TestDatadogMonitor_import
--- PASS: TestDatadogMonitor_import (4.78s)
=== RUN   TestDatadogUser_import
--- PASS: TestDatadogUser_import (4.27s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccDatadogDowntime_Basic
--- PASS: TestAccDatadogDowntime_Basic (1.97s)
=== RUN   TestAccDatadogDowntime_BasicMultiScope
--- PASS: TestAccDatadogDowntime_BasicMultiScope (2.69s)
=== RUN   TestAccDatadogDowntime_BasicNoRecurrence
--- PASS: TestAccDatadogDowntime_BasicNoRecurrence (14.37s)
=== RUN   TestAccDatadogDowntime_BasicUntilDateRecurrence
--- PASS: TestAccDatadogDowntime_BasicUntilDateRecurrence (6.32s)
=== RUN   TestAccDatadogDowntime_BasicUntilOccurrencesRecurrence
--- PASS: TestAccDatadogDowntime_BasicUntilOccurrencesRecurrence (2.28s)
=== RUN   TestAccDatadogDowntime_WeekDayRecurring
--- PASS: TestAccDatadogDowntime_WeekDayRecurring (2.08s)
=== RUN   TestAccDatadogDowntime_Updated
--- PASS: TestAccDatadogDowntime_Updated (4.47s)
=== RUN   TestAccDatadogDowntime_TrimWhitespace
--- PASS: TestAccDatadogDowntime_TrimWhitespace (2.47s)
=== RUN   TestResourceDatadogDowntimeRecurrenceTypeValidation
--- PASS: TestResourceDatadogDowntimeRecurrenceTypeValidation (0.00s)
=== RUN   TestResourceDatadogDowntimeRecurrenceWeekDaysValidation
--- PASS: TestResourceDatadogDowntimeRecurrenceWeekDaysValidation (0.00s)
=== RUN   TestAccDatadogMetricMetadata_Basic
--- PASS: TestAccDatadogMetricMetadata_Basic (4.47s)
=== RUN   TestAccDatadogMetricMetadata_Updated
--- PASS: TestAccDatadogMetricMetadata_Updated (9.25s)
=== RUN   TestAccDatadogMonitor_Basic
--- PASS: TestAccDatadogMonitor_Basic (2.37s)
=== RUN   TestAccDatadogMonitor_BasicNoTreshold
--- PASS: TestAccDatadogMonitor_BasicNoTreshold (2.30s)
=== RUN   TestAccDatadogMonitor_Updated
--- PASS: TestAccDatadogMonitor_Updated (4.32s)
=== RUN   TestAccDatadogMonitor_TrimWhitespace
--- PASS: TestAccDatadogMonitor_TrimWhitespace (2.38s)
=== RUN   TestAccDatadogMonitor_Basic_float_int
--- PASS: TestAccDatadogMonitor_Basic_float_int (4.60s)
=== RUN   TestAccDatadogTimeboard_update
--- PASS: TestAccDatadogTimeboard_update (7.06s)
=== RUN   TestValidateAggregatorMethod
--- PASS: TestValidateAggregatorMethod (0.00s)
=== RUN   TestAccDatadogUser_Updated
--- PASS: TestAccDatadogUser_Updated (6.89s)
PASS
ok  	terraform-provider-datadog/datadog	93.346s
```

**Comment by jamesmharvey** [comment]
@paddycarver @bflad @tombuildsstuff @catsby I based this off of https://github.com/terraform-providers/terraform-provider-datadog/pull/34 so we can use the fix for #33 in production. Please let me know if there's anything else I can provide.

**Comment by jamesmharvey** [comment]
Sure thing @tombuildsstuff . Do you think you could get this tagged into a 1.0.2 release?

**Comment by catsby** [comment]
@jamesmharvey while the API ver 2.7 added support for recovery thresholds, this pull request only updates the vendored SDK. The features for recovery thresholds still need to be added to the resource(s) that would use them, am I right? Assuming so, unless this SDK update fixes some other bugs, a new `1.0.2` release wouldn't contain much. Unless I'm missing something 😄

**Comment by jamesmharvey** [comment]
Ah, yup, you're right.

**Pull request merged**
