### PR TITLE
[dashboards] Support importing dashboards using the new string id + update to the latest go-datadog-api 

### PR DESCRIPTION
**Pull request by enbashi**
Fixes: https://github.com/terraform-providers/terraform-provider-datadog/issues/163. Adds the ability to import existing  screenboards and timeboards using the new string ID format.
This functionality relies on a change in the Go client that is in ~an open~ (now merged) PR: https://github.com/zorkian/go-datadog-api/pull/225

### CODE REVIEW

**Comment by ParthKolekar** [comment]
Could we have this merged in? I also note that travis-ci is being weird for this build and some tests are possibly failing.

**Comment by bkabrda** [comment]
Hi, since https://github.com/zorkian/go-datadog-api/pull/225 has been merged, could you update the go-datadog-api dependency in this PR so that we could merge it? LGTM otherwise :+1:

**Comment by enbashi** [comment]
> Hi, since [zorkian/go-datadog-api#225](https://github.com/zorkian/go-datadog-api/pull/225) has been merged, could you update the go-datadog-api dependency in this PR so that we could merge it? LGTM otherwise 👍

@bkabrda done!

**Comment by enbashi** [comment]
@bkabrda my tests were failing until I updated the vendors directory with the latest versions using `go mod vendor` which resulted in big changes. Could you please take a look and let me know whether this is good to merge or you want me to revert the update. Thanks!

**Comment by enbashi** [comment]
Closing this PR. Please merge https://github.com/terraform-providers/terraform-provider-datadog/pull/184 instead with better and cleaner commit history.

**Pull request closed without merging**
