### PR TITLE
Implement monitor_id support for downtime

### PR DESCRIPTION
**Pull request by cvbarros**
This PR is a shot at trying to implement the `monitor_id` field for downtime.
Since this is my first PR for terraform, please let me know if there are any hard mistakes, and I'll more than happy to work through them.

### CODE REVIEW

**Comment by nyanshak** [comment]
I'd suggest also changing the docs to mention this new (optional?) field: https://github.com/terraform-providers/terraform-provider-datadog/blob/master/website/docs/r/downtime.html.markdown.

Also, I think you should check for errors on Sets, similar to @yfronto's proposed change (#27):
```
if err := d.Set("title", timeboard.GetTitle()); err != nil {
	return err
}
```

Otherwise, LGTM :)

**Comment by cvbarros** [comment]
Hey @nyanshak, thanks for looking into this. 
I fixed some problems with acceptance tests and implemented  the changes you suggested.

**Comment by HontoNoRoger** [comment]
@nyanshak Could we please get this into the master?

**Comment by yfronto** [comment]
@HontoNoRoger HashiCorp manages this repo. I think @tombuildsstuff might be the right contact to ping on this.

**Comment by nyanshak** [comment]
(I really wish I could get it merged into master but I don't have the right permissions. Sorry @HontoNoRoger)

**Comment by tombuildsstuff** [comment]
Tests pass:

screen shot 2018-01-03 at 16 16 48

**Comment by kikitux** [comment]
https://github.com/terraform-providers/terraform-provider-datadog/issues/25

**Pull request merged**
