### PR TITLE
Using accessors, adding err checks

### PR DESCRIPTION
**Pull request by yfronto**
* Addresses #20 and #19
* Most calls to `schema.ResourceData.Set` failed to check returned error, surpressing actual errors
* Zorkian's `go-datadog-api.v2` uses accessor methods and not all the provider code was updated
* Switched to using kr/pretty logging to dump objects during debug
* Changed events, groups, and scopes from `schema.TypeSet` to `schema.TypeList`, there were errors that were resolved by moving to `TypeList`. I don't know if this was the right path, maybe we could revisit making these sets in the future. Errors were like this:
```
* module.datadog_timeboard.my_timeboard: datadog_timeboard.my_timeboard: Invalid address to set: []string{"graph", "2", "scope"}
```

### CODE REVIEW

**Comment by nyanshak** [comment]
I just tested this and now changes in the UI are reflected in terraform plan (reverting manual changes back to the expected state).

@radeksimko I'd love to get this merged and tagged with a new version (0.1.1?). Pinging for review

**Comment by nyanshak** [comment]
@radeksimko @grubernaut @stack72 

This is a hugely important bug-fix. Don't mean to be annoying, but can we get a review and either merge or some feedback on what needs to change?

As an aside, if this repo is not one that you're keen on maintaining (lack of visibility, don't use datadog, or lack of interest), I'd be willing to discuss getting additional people write access to this repo. If that's something that you're interested in, let me know.

**Comment by grubernaut** [comment]
Hey @nyanshak, sorry this hasn't been merged for you yet. Although @stack72 and myself are no longer employees at HashiCorp. @catsby, @tombuildsstuff, and @apparentlymart are though!

**Comment by nyanshak** [comment]
My bad! I was going based off most recently merged commits :'(

**Comment by apparentlymart** [comment]
Thanks for this @yfronto, @nyanshak!

Sorry for the delay in reviewing this. We're about to head into the next major release period and so we've been more heads-down than usual, unfortunately. :confounded:

**Pull request merged**
