### PR TITLE
#148 Fix log monitor UI issue: generate queryConfig.queryString from query

### PR DESCRIPTION
**Pull request by geekeren**
Fix log monitor UI issue of the search query
-  generate queryConfig.queryString from the query attribute

### CODE REVIEW

**Comment by bkabrda** [comment]
So overall this looks great, I'd just like to ask you to create a function for the piece of code that is (AFAICS) completely the same and used in two parts of your patch - the piece that starts with `matchStrs := ...` - let's avoid code duplication.

**Comment by geekeren** [comment]
> So overall this looks great, I'd just like to ask you to create a function for the piece of code that is (AFAICS) completely the same and used in two parts of your patch - the piece that starts with `matchStrs := ...` - let's avoid code duplication.

You're right, I am going to do that.

**Comment by geekeren** [comment]
@bkabrda I have refactored it, could you take a look?

**Comment by bkabrda** [comment]
Yeah, LGTM now :+1:, merging. Thanks a lot for the PR!

**Comment by gregsymons** [comment]
I've been waiting for this bug to get fixed. Any idea when the next release will be?

**Comment by bkabrda** [comment]
@gregsymons hopefully within next two weeks, but it's definitely something that can change. Hope this is ok for you.

**Pull request merged**
