### PR TITLE
Add legend_size to api request

### LINKED ISSUE #420: Missing legend_size on datadog_dashboard
The new datadog_dashboard resource does not include legend_size on widgets defined with timeseries_definition, like the datadog_screenboard resource used to include.

### Affected Resource(s)

datadog_dashboard

### Expected Behavior
There should be a way to set legend_size

### Actual Behavior
There is no way to set legend size

### PR DESCRIPTION
**Pull request by matthewduren**
Closes #420

### CODE REVIEW

**Comment by matthewduren** [comment]
> I looks good, however we should probably include a validation as only following values are supported:
> 
> * 2
> * 4
> * 8
> * 16
> * auto

@jirikuncar all set. I considered also adding a test for this, but I don't see other cases where validation is being tested so I didn't add such a test.

**Comment by bkabrda** [comment]
Hey @matthewduren, awesome work! The PR looks ok, but there's one more thing I'd like to request: we recently started recording the interactions with the DD API using "cassettes" to be able to run all tests fast and without internet connection - more details on that in [1]. Could you please rebase on latest master and regenerate cassette for the test you touched with `make cassettes TESTARGS="-run TestAccDatadogDashboard_update"`? (Do note that this will actually interact with the DD API much like acceptance tests, so make sure you don't provide api/app keys for a production org).

Alternatively, if you don't/can't do this, I'd be happy to add a commit to this PR updating the cassettes, assuming you give me access to your branch from which you did this PR.

[1] https://github.com/terraform-providers/terraform-provider-datadog#developing-the-provider

**Comment by matthewduren** [comment]
> Hey @matthewduren, awesome work! The PR looks ok, but there's one more thing I'd like to request: we recently started recording the interactions with the DD API using "cassettes" to be able to run all tests fast and without internet connection - more details on that in [1]. Could you please rebase on latest master and regenerate cassette for the test you touched with `make cassettes TESTARGS="-run TestAccDatadogDashboard_update"`? (Do note that this will actually interact with the DD API much like acceptance tests, so make sure you don't provide api/app keys for a production org).
> 
> Alternatively, if you don't/can't do this, I'd be happy to add a commit to this PR updating the cassettes, assuming you give me access to your branch from which you did this PR.
> 
> [1] https://github.com/terraform-providers/terraform-provider-datadog#developing-the-provider

No worries, will update with this addition next week.

**Comment by matthewduren** [comment]
I'm not sure what I've done wrong here, but I appear to have missed something, somewhere.

**Comment by nmuesch** [comment]
Hey @matthewduren I think this PR is pretty much good to go, thanks for working on it! I noticed there is some user data, like email in the recorded cassette. If I could get write access to this branch I'd be happy to create a recording from a dedicated account and commit over the existing recording.

**Comment by matthewduren** [comment]
Ah sure, I wasn't sure so I just setup a demo account. Please force push over that if you can to keep out the clutter. Once you accept the invite I'll make sure you have the appropriate permissions.

**Comment by nmuesch** [comment]
Hey @matthewduren thanks, I just accepted. I'll try to update the recordings tomorrow and get this merged in 🙇

**Comment by nmuesch** [comment]
Hey @matthewduren I wound up pushing to your fork, but it looks like its based on the mater branch. As an alternative, what do you think if we just drop the commits modifying the cassettes, we can merge, and I can update the cassettes in a PR directly after. (Note we're looking into ways of improving this process, so thanks for working on this 😄)

Would you be up for doing that?

**Comment by nmuesch** [comment]
Apologies for my delay here @matthewduren . Going to go ahead and merge this in now and commit the updated cassettes separately. Thanks again for the work here!

**Pull request merged**
